//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderedfooditem
    {
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> FoodId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual tbl_fooditems tbl_fooditems { get; set; }
    }
}
