//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int CId { get; set; }
        public string OrderNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<bool> CustomerType { get; set; }
        public Nullable<int> WaiterId { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual tbl_table tbl_table { get; set; }
        public virtual tbl_waiter tbl_waiter { get; set; }
    }
}
