//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fooditems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_fooditems()
        {
            this.tbl_orderedfooditem = new HashSet<tbl_orderedfooditem>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string Price { get; set; }
        public byte Status { get; set; }
        public byte IsSpecial { get; set; }
        public string Discount { get; set; }
        public byte[] Image { get; set; }
        public string FoodName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_orderedfooditem> tbl_orderedfooditem { get; set; }
    }
}
